### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [yorkittran/google-scraper#9]
Hello Tuan  👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have completed the first round of code reviews, but note that #11 prevented me from checking every feature yet. So this issue should be solved first. I also look forward to your feedback on the other open issues.

**Comment by yorkittran** [comment]
Sorry for the late response @olivierobert, I have just received this today. Unfortunately, I have a busy plan tomorrow so could we move it to the weekend? I will handle all these issues before the start of next week.

**Comment by olivierobert** [comment]
Sure. I will then review your feedback on the following Monday 😁

**Comment by olivierobert** [comment]
I have now reviewed your feedback and fixes for the open issues. I noticed that you did not have any for #14 😢 

In any case, we now have sufficient information to wrap up this stage of the recruitment process. So we appreciate your efforts so far 🙏 Our team will contact you shortly by email about the next steps.
